services:
  my-nginx-service:
    image: nginx
  web:
    image: atulkhot/rk8s-py:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - "atulkhot/rk8s-py:${TAG:-latest}"
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
    volumes:
      - mywebdata:/app/data
  my-redis-service:
    image: redis
    volumes:
      - myredisdata:/data
 
volumes:
  mywebdata:
  myredisdata:
