name: Compose - Build, Push & Deploy
 
on:
  workflow_dispatch:
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DH_USER: $glossterm::[ secrets.DOCKERHUB_USERNAME ]
      REPO: $glossterm::[ secrets.DOCKERHUB_REPO ]
      SSH_OPTS: '-o StrictHostKeyChecking=no'
      REMOTE: 'ubuntu@$glossterm::[ secrets.AKAMAI_INSTANCE_IP_ADDRESS ]'
      REMOTE_APP_DIR: '/opt/app'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: $glossterm::[ secrets.DOCKERHUB_USERNAME ]
        password: $glossterm::[ secrets.DOCKERHUB_TOKEN ]
    - name: Build the Docker image
      run: |
        docker build -f Dockerfile \
          -t "pass:[\(DH_USER/\)]REPO:latest" \
          -t "pass:[\(DH_USER/\)]REPO:$glossterm::[ github.sha ]" \
          .
    - name: Push the Docker image to Docker Hub
      run: |
        docker push "pass:[\(DH_USER/\)]REPO" --all-tags
