name: Compose - Build, Push & Deploy
 
on:
  workflow_dispatch:
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DH_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      REPO: ${{ secrets.DOCKERHUB_REPO }}
      SSH_OPTS: '-o StrictHostKeyChecking=no'
      REMOTE: 'ubuntu@${{ secrets.AKAMAI_INSTANCE_IP_ADDRESS }}'
      REMOTE_APP_DIR: '/opt/app'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        docker build -f Dockerfile \
          -t "$DH_USER/$REPO:latest" \
          -t "$DH_USER/$REPO:${{ github.sha }}" \
          .
    - name: Push the Docker image to Docker Hub
      run: |
        docker push "$DH_USER/$REPO" --all-tags
    - name: Login to Docker Hub on VM
      run: |
        ssh $SSH_OPTS $REMOTE <<EOF
          docker login -u $DH_USER -p ${{ secrets.DOCKERHUB_TOKEN }}
        EOF
    - name: Create .env file
      run: |
        echo "MY_SECRET_KEY=${{ secrets.MY_SECRET_KEY }}" >> .env
        echo "API_ENDPOINT=${{ secrets.API_ENDPOINT }}" >> .env
    - name: Ensure remote directory exists
      run: |
        ssh $SSH_OPTS $REMOTE sudo mkdir -p $REMOTE_APP_DIR
    - name: Copy GitHub Actions .env file to Remote VM
      run: |
        scp $SSH_OPTS .env $REMOTE:$REMOTE_APP_DIR/.env
    - name: Run Docker Compose
      run: |
        ssh $SSH_OPTS $REMOTE << EOF
          cd $REMOTE_APP_DIR
          # run containers
          docker compose up -d
        EOF
    - name: Clean up .env file
      run: rm .env
    - name: Clean up SSH private key
      run: rm ~/.ssh/id_rsa

